export const REQUEST_ARTISTS = 'REQUEST_ARTISTS';
export const RECEIVE_ARTISTS = 'RECEIVE_ARTISTS';
export const REQUEST_ARTIST_DETAILS = 'REQUEST_ARTIST_DETAILS';
export const RECEIVE_ARTIST_DETAILS = 'RECEIVE_ARTIST_DETAILS';
export const REQUEST_ARTIST_ALBUMS = 'REQUEST_ARTIST_ALBUMS';
export const RECEIVE_ARTIST_ALBUMS = 'RECEIVE_ARTIST_ALBUMS';